# Generated by Django 6.0.5 on 2026-05-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
