# Generated by Django 6.0.5 on 2026-05-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_customer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
