# Generated by Django 6.0.5 on 2026-05-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_alter_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
